#!/bin/sh

set -eu

DIST=${1:-70}

case $DIST in
	40) NAME=etch ;;
	50) NAME=lenny ;;
	60) NAME=squeeze ;;
	70) NAME=wheezy ;;
	*) echo "Dist version $DIST unknown" >2
	   exit 1 ;;
esac

dch --local "~pgapt${DIST}+" --force-distribution --distribution "$NAME-pgapt" \
	"Rebuild for apt.postgresql.org."

dpkg-buildpackage -b
