= apt.postgresql.org

Policy draft: http://wiki.debian.org/pkg-postgresql/Workflow

== dependencies

Not much, to install them:

  make build-depends

Also you have to add a +deb-src+ line that points to sid so that +apt-get
source+ will consider the right versions of the source packages.

== how does it work?

It's based on makefiles:

  make postgresql
  make OUT=/path/to/where/to/build postgresql-8.4

Rules provided:

build-depends::
	will use +sudo apt-get install+ to bring in all dependencies
	required to run the +apt.postgresql.org+ scripts.

setup::
	setup the debian repositories, using +bzr clone+

postgresql::
	builds the postgresql versions 8.3 8.4 9.0 and 9.1 for the current
	architecture (the one the script is executed on)

extensions::
	builds all supported postgresql extensions

postgresql-common::
	build an installs the latest +postgresql-common+, +postgresql-client-common+
	and +postgresql-server-dev-all+ packages, which are needed for
	building the other packages.  The +postgresql+ target includes it.

== supported extensions

See +pgsql/Makefile+, both the +EXTENSIONS+ variable and the +extensions+
target.  To add support for an extension, first add its debian source
package name to the +EXTENSIONS+ list and check that it builds.  If it's ok
you're done, if not, remove from the list and add a special target, where
you have to add-in whatever it takes to make the extension builds properly.

