#!/bin/sh

set -eu

[ "$USER" = "aptuser" ] || SUDO="sudo -u aptuser"
export REPREPRO_BASE_DIR="/srv/apt/repo"
REPREPRO="reprepro -b $REPREPRO_BASE_DIR --morguedir $REPREPRO_BASE_DIR/morgue --verbose"
DISTS="sid wheezy squeeze precise lucid"

while getopts "d:" opt ; do
	case $opt in
		d) DISTS="$OPTARG" ;;
		*) exit 5 ;;
	esac
done
# shift away args
shift $(($OPTIND - 1))

PKG="$1"

set -x

$REPREPRO ls $PKG

for DIST in $DISTS ; do
	${SUDO:-} $REPREPRO copysrc $DIST-pgdg $DIST-pgdg-testing $PKG
done

$REPREPRO ls $PKG
