usr/include/postgresql/internal/*
usr/include/postgresql/libpq-fe.h
#usr/include/postgresql/libpq-events.h
usr/include/postgresql/libpq/libpq-fs.h
usr/include/postgresql/pg_config*.h
usr/include/postgresql/postgres_ext.h
usr/include/postgresql/8.2/server/catalog/pg_type.h /usr/include/postgresql/catalog
#usr/include/postgresql/8.2/server/catalog/genbki.h /usr/include/postgresql/catalog
usr/include/postgresql/8.2/server/nodes/nodes.h /usr/include/postgresql/nodes
usr/include/postgresql/8.2/server/utils/{elog,errcodes,palloc}.h /usr/include/postgresql/utils
usr/include/postgresql/8.2/server/{c,pg_config,pg_config_manual,pg_config_os,port,pg_trace}.h /usr/include/postgresql/
usr/include/postgresql/8.2/server/postgres{,_fe,_ext}.h /usr/include/postgresql/
usr/include/postgresql/8.2/server/mb/pg_wchar.h /usr/include/postgresql/mb
usr/lib/libpgport.a
usr/lib/libpq.a
usr/lib/libpq.so
usr/lib/postgresql/8.2/bin/pg_config usr/bin
usr/share/locale/*/LC_MESSAGES/pg_config-8.2.mo
usr/share/postgresql/8.2/man/man1/pg_config.1 /usr/share/man/man1
