#!/bin/sh

HOST="atalia.postgresql.org"
QUEUE="${1:-incoming}"

trap "rm -rf *" 0 2 3 15

ls -AlR

set -eux

CHANGES="$(find . -name '*.changes' -not -name '*_source.changes')"

dcmd rsync -av $CHANGES $HOST:/srv/apt/$QUEUE

# call processincoming.sh once for all packages uploaded
ssh $HOST /srv/apt/processincoming.sh $QUEUE

# trap will clean up here
